# Generated by Django 4.1.3 on 2022-11-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidshare', '0003_video_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.ManyToManyField(related_name='videos', to='vidshare.category'),
        ),
    ]
