# Generated by Django 4.1.3 on 2022-11-07 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vidshare', '0004_category_video_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
    ]
