# Generated by Django 4.1.2 on 2022-11-11 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidshare', '0005_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
