# Generated by Django 4.1.3 on 2022-11-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vidshare', '0006_author_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='category',
            field=models.ManyToManyField(null=True, to='vidshare.category'),
        ),
    ]
